### your site title here
#Start The Localhost : bundle exec jekyll serve --incremental --trace

title: Kevin Pratama Setiawan
description: Fullstack and Cloud Developer | Informatics Engineering Student | Based in Indonesia

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: kevinpratama.kps@gmail.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "linkedin.com/in/kevin-pratama-setiawan-159060258"
github: "https://github.com/KevinPratamaSetiawan"
instagram: "https://www.instagram.com/kev1n_pratama/"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
  
  leetcases:
    output: true
    permalink: /leetcases/:name/
  
  certifications:
    output: true
    permalink: /certifications/:name/
    order:
      - bangkit1.md
      - dicoding1.md
      - dicoding2.md
      - dicoding3.md
      - dicoding4.md
      - dicoding5.md
      - dicoding6.md
      - dicoding7.md
      - dicoding8.md
      - dicoding9.md
      - dicoding10.md
      - dicoding11.md
      - coursera1.md
      - coursera2.md
      - coursera3.md
      - coursera4.md
      - coursera5.md
      - coursera6.md
      - coursera7.md
      - coursera8.md
      - coursera9.md
      - coursera10.md
      - coursera11.md
      - coursera12.md
      - coursera13.md
      - coursera14.md
      - coursera15.md
      - google1.md
      - google2.md
      - google3.md
      - google4.md
      - google5.md
      - google6.md
      - google7.md
      - google8.md
      - google9.md
      - google10.md
      - google11.md
      - google12.md
      - google13.md
      - google14.md
      - google15.md
      - google16.md
      - google17.md
      - google18.md
      - google19.md
      - google20.md
      - google21.md
      - google22.md
      - google23.md
      - google24.md
      - google25.md
      - google26.md
      - google27.md
      - google28.md
      - google29.md

mp3_order:
  thePopOut:
    - Control.mp3
    - Black Friday.mp3
    - Medics.mp3
    - The Story Of Adidon.mp3
    - First Person Shooter.mp3
    - Like That.mp3
    - 7 Minute Drill.mp3
    - Push Ups.mp3
    - euphoria.mp3
    - 6_16 in LA.mp3
    - FAMILY MATTERS.mp3
    - meet the grahams.mp3
    - life goes on.mp3
    - Not Like Us.mp3
    - The Greatest.mp3
  playlist1:
    - Adonis Interlude.mp3
    - 16.mp3
    - a m a r i.mp3
    - A.D.H.D.mp3
    - All My Life.mp3
    - Alright.mp3
    - AMERICA HAS A PROBLEM.mp3
    - Annihilate.mp3
    - a lot.mp3
    - Backseat Freestyle.mp3
    - Bad Blood.mp3
    - Better Now.mp3
    - Big Shot.mp3
    - Bitch Don't Kill My Vibe.mp3
    - Black Friday.mp3
    - Bless Up.mp3
    - Brand New.mp3
    - Calling.mp3
    - Cash In Cash Out.mp3
    - Control.mp3
    - Count Me Out.mp3
    - Dance Now.mp3
    - Die Hard.mp3
    - Diet Coke.mp3
    - DNA.mp3
    - DOGTOOTH.mp3
    - Don't Do It.mp3
    - Down Bad.mp3
    - dreamy night.mp3
    - EARFQUAKE.mp3
    - ELEMENT.mp3
    - FAMILY MATTERS.mp3
    - Family ties.mp3
    - Father Stretch My Hands Pt. 1.mp3
    - First Person Shooter.mp3
    - Follow God.mp3
    - Fuck Your Ethnicity.mp3
    - Fuckin' Problems.mp3
    - Good News.mp3
    - HEAVEN TO ME.mp3
    - Hol' Up.mp3
    - hooligan.mp3
    - How Much A Dollar Cost.mp3
    - How To Love.mp3
    - HUMBLE.mp3
    - i.mp3
    - I Like You (A Happier Song).mp3
    - I'm Better.mp3
    - issues.mp3
    - King Kunta.mp3
    - 3005.mp3
    - King's Dead.mp3
    - LA Leakers 1.1.mp3
    - LA Leakers 1.2.mp3
    - Ladders.mp3
    - LOYALTY.mp3
    - M.a.a.D. city.mp3
    - Mask Off.mp3
    - Mean Street.mp3
    - Mona Lisa.mp3
    - Money Trees.mp3
    - N95.mp3
    - New Freezer.mp3
    - no sense.mp3
    - Nosetalgia.mp3
    - Only Need.mp3
    - Opps.mp3
    - Paramedic!.mp3
    - Potato Salad.mp3
    - Praise The Lord (Da Shine).mp3
    - Pray For Me.mp3
    - PRIDE.mp3
    - Rich Spirit.mp3
    - RIOT (Rowdy Pipe'n).mp3
    - rockstar.mp3
    - Savior.mp3
    - SEE YOU AGAIN.mp3
    - Self Care.mp3
    - SICKO MODE.mp3
    - Stay.mp3
    - Stick.mp3
    - Sunflower.mp3
    - Surround Sound.mp3
    - Swimming Pool.mp3
    - The Blacker The Berry.mp3
    - The Heart part 5.mp3
    - The Hillbillies.mp3
    - The Story Of Adidon.mp3
    - This is a Satire by Kendrick Lamar.mp3
    - TPAB.mp3
    - Tribe.mp3
    - untitled [8 - 2].mp3
    - Vanity Slave.mp3
    - Vegas.mp3
    - Vent.mp3
    - WHARF TALK.mp3
    - What's Up Danger.mp3
    - Workin' Out.mp3
    - Am I Dreaming.mp3
    - Under The Sun (with J. Cole & Lute feat. DaBaby).mp3
    - 1985.mp3
    - Oklama Rich Spirit.mp3
    - Medics.mp3
    - Wow Freestyle.mp3
    - XXX.mp3
    - Ric Flair Drip.mp3
    - Kant Nobody.mp3
    - The London.mp3
    - Ni__as In Paris.mp3
    - You're an Ace, Kid.mp3
    - wanting, getting, wanting.mp3
    - take the bait.mp3
    - dark hour.mp3
    - fake ass gold.mp3
    - end of a life.mp3
    - Umeda Night Fever 19'.mp3
    - Travolta Costum.mp3
    - Like That.mp3
    - 7 Minute Drill.mp3
    - Push Ups.mp3
    - euphoria.mp3
    - 6_16 in LA.mp3
    - life goes on.mp3
    - Not Like Us.mp3
    - Dior.mp3

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
