### your site title here
#Start The Localhost : bundle exec jekyll serve --incremental --trace

title: Kevin Pratama Setiawan
description: Fullstack and Cloud Developer | Informatics Engineering Student | Based in Indonesia

baseurl: "" #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository
email: kevinpratama.kps@gmail.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "linkedin.com/in/kevin-pratama-setiawan-159060258"
github: "https://github.com/KevinPratamaSetiawan"
instagram: "https://www.instagram.com/kev1n_pratama/"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
  
  leetcases:
    output: true
    permalink: /leetcases/:name/
  
  certifications:
    output: true
    permalink: /certifications/:name/
    order:
      - bangkit1.md
      - dicoding1.md
      - dicoding2.md
      - dicoding3.md
      - dicoding4.md
      - dicoding5.md
      - dicoding6.md
      - dicoding7.md
      - dicoding8.md
      - dicoding9.md
      - dicoding10.md
      - dicoding11.md
      - coursera1.md
      - coursera2.md
      - coursera3.md
      - coursera4.md
      - coursera5.md
      - coursera6.md
      - coursera7.md
      - coursera8.md
      - coursera9.md
      - coursera10.md
      - coursera11.md
      - coursera12.md
      - coursera13.md
      - coursera14.md
      - coursera15.md
      - google1.md
      - google2.md
      - google3.md
      - google4.md
      - google5.md
      - google6.md
      - google7.md
      - google8.md
      - google9.md
      - google10.md
      - google11.md
      - google12.md
      - google13.md
      - google14.md
      - google15.md
      - google16.md
      - google17.md
      - google18.md
      - google19.md
      - google20.md
      - google21.md
      - google22.md
      - google23.md
      - google24.md
      - google25.md
      - google26.md
      - google27.md
      - google28.md
      - google29.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
